name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
      - run: brew install rpm
      - run: npm ci
      - run: npm test
      - run: npm run dist
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.AppImage,dist/*.deb,dist/*.dmg,dist/*.exe,dist/*.rpm,dist/*.tar.bz2,dist/*.zip,dist/*.blockmap,dist/latest*.yml"
          token: ${{ secrets.GITHUB_TOKEN }}
